<?php

/**
 * FlatFile Blog Configuration
 * Generated by install.php
 */

// Site Configuration
define('SITE_TITLE', 'Crazy Blogger');
define('BASE_URL', 'http://localhost/blogs/');
define('ADMIN_USERNAME', 'admin');
define('ADMIN_EMAIL', 'admin@admin.com');
define('TIMEZONE', 'Asia/Kolkata');

// Security
define('ADMIN_PASSWORD_HASH', '$2y$10$knCSvLKQey5OCmFg6DPkYedWMFBWV9PA6crt5cEQF6kyVAUbCqu1O');
define('CSRF_TOKEN_NAME', 'csrf_token');
define('SESSION_TIMEOUT', 3600); // 1 hour

// Directories
define('CONTENT_DIR', __DIR__ . '/content/');
define('POSTS_DIR', __DIR__ . '/content/posts/');
define('UPLOADS_DIR', __DIR__ . '/uploads/');
define('LOGS_DIR', __DIR__ . '/logs/');

// Create logs directory if it doesn't exist
if (!file_exists(LOGS_DIR)) {
    mkdir(LOGS_DIR, 0755, true);
}

// Security Settings
define('MAX_UPLOAD_SIZE', 5 * 1024 * 1024); // 5MB
define('ALLOWED_IMAGE_TYPES', ['image/jpeg', 'image/png', 'image/gif', 'image/webp']);
define('THUMBNAIL_SIZE', 300);
define('MEDIUM_SIZE', 800);

// Performance
define('CACHE_ENABLED', true);
define('CACHE_DURATION', 3600); // 1 hour

// Development
define('DEBUG_MODE', false);
define('LOG_LEVEL', 'INFO');

// Production Settings
define('ENVIRONMENT', 'production');
define('MAINTENANCE_MODE', false);

// Error handling for production
if (!DEBUG_MODE) {
    error_reporting(0);
    ini_set('display_errors', 0);
    ini_set('log_errors', 1);
    ini_set('error_log', LOGS_DIR . 'error.log');
} else {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
}

// Set timezone
if (defined('TIMEZONE')) {
    date_default_timezone_set(TIMEZONE);
}

// Security headers
if (!headers_sent()) {
    header('X-Content-Type-Options: nosniff');
    header('X-Frame-Options: DENY');
    header('X-XSS-Protection: 1; mode=block');
    header('Referrer-Policy: strict-origin-when-cross-origin');
}

// Note: Direct access protection is handled by .htaccess file
