<?php

/**
 * FlatFile Blog Installation Script
 * 
 * This script sets up the entire blog system automatically.
 * Run this once to install the blog system.
 */

// Check if already installed
$already_installed = file_exists('config.php') && file_exists('content/index.json');

// Set error reporting
error_reporting(E_ALL);
ini_set('display_errors', 1);

// Installation status
$installation_steps = [];
$errors = [];
$success = true;

// Function to add installation step
function addStep($step, $status = 'success')
{
    global $installation_steps;
    $installation_steps[] = ['step' => $step, 'status' => $status];
}

// Function to add error
function addError($error)
{
    global $errors, $success;
    $errors[] = $error;
    $success = false;
}

// Handle reinstall action
if (isset($_POST['action']) && $_POST['action'] === 'reinstall') {
    // Delete existing files
    $files_to_delete = [
        'config.php',
        'content/index.json',
        'content/settings.json'
    ];

    $directories_to_delete = [
        'content/posts',
        'uploads/featured',
        'logs'
    ];

    foreach ($files_to_delete as $file) {
        if (file_exists($file)) {
            unlink($file);
        }
    }

    foreach ($directories_to_delete as $dir) {
        if (is_dir($dir)) {
            $files = glob($dir . '/*');
            foreach ($files as $file) {
                if (is_file($file)) {
                    unlink($file);
                }
            }
            rmdir($dir);
        }
    }

    // Remove empty directories
    if (is_dir('content') && count(scandir('content')) == 2) {
        rmdir('content');
    }
    if (is_dir('uploads') && count(scandir('uploads')) == 2) {
        rmdir('uploads');
    }
    if (is_dir('logs') && count(scandir('logs')) == 2) {
        rmdir('logs');
    }

    addStep("Removed existing installation files");
    $already_installed = false;
}

// Check if form was submitted
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !isset($_POST['action'])) {
    $site_title = trim($_POST['site_title'] ?? '');
    $site_description = trim($_POST['site_description'] ?? '');
    $admin_username = trim($_POST['admin_username'] ?? '');
    $admin_email = trim($_POST['admin_email'] ?? '');
    $admin_password = trim($_POST['admin_password'] ?? '');
    $timezone = trim($_POST['timezone'] ?? '');
    $base_url = trim($_POST['base_url'] ?? '');

    // Validate inputs
    if (empty($site_title)) {
        addError('Site title is required');
    }
    if (empty($admin_username)) {
        addError('Admin username is required');
    }
    if (empty($admin_email) || !filter_var($admin_email, FILTER_VALIDATE_EMAIL)) {
        addError('Valid admin email is required');
    }
    if (empty($admin_password) || strlen($admin_password) < 6) {
        addError('Admin password must be at least 6 characters');
    }
    if (empty($timezone)) {
        addError('Timezone is required');
    }
    if (empty($base_url)) {
        addError('Base URL is required');
    }

    if ($success) {
        // Step 1: Create directories
        $directories = [
            'content',
            'content/posts',
            'content/backups',
            'uploads',
            'uploads/featured',
            'assets',
            'assets/css',
            'assets/js',
            'libs',
            'logs',
            'admin',
            'admin/tools'
        ];

        foreach ($directories as $dir) {
            if (!file_exists($dir)) {
                if (mkdir($dir, 0755, true)) {
                    addStep("Created directory: $dir");
                } else {
                    addError("Failed to create directory: $dir");
                }
            } else {
                addStep("Directory already exists: $dir");
            }
        }

        // Step 2: Create config.php
        $config_content = "<?php
/**
 * FlatFile Blog Configuration
 * Generated by install.php
 */

// Site Configuration
define('SITE_TITLE', '" . addslashes($site_title) . "');
define('BASE_URL', '" . rtrim($base_url, '/') . "/');
define('ADMIN_USERNAME', '" . addslashes($admin_username) . "');
define('ADMIN_EMAIL', '" . addslashes($admin_email) . "');
define('TIMEZONE', '" . addslashes($timezone) . "');

// Security
define('ADMIN_PASSWORD_HASH', '" . password_hash($admin_password, PASSWORD_DEFAULT) . "');
define('CSRF_TOKEN_NAME', 'csrf_token');
define('SESSION_TIMEOUT', 3600); // 1 hour

// Directories
define('CONTENT_DIR', __DIR__ . '/content/');
define('POSTS_DIR', __DIR__ . '/content/posts/');
define('UPLOADS_DIR', __DIR__ . '/uploads/');
define('LOGS_DIR', __DIR__ . '/logs/');

// Create logs directory if it doesn't exist
if (!file_exists(LOGS_DIR)) {
    mkdir(LOGS_DIR, 0755, true);
}

// Security Settings
define('MAX_UPLOAD_SIZE', 5 * 1024 * 1024); // 5MB
define('ALLOWED_IMAGE_TYPES', ['image/jpeg', 'image/png', 'image/gif', 'image/webp']);
define('THUMBNAIL_SIZE', 300);
define('MEDIUM_SIZE', 800);

// Performance
define('CACHE_ENABLED', true);
define('CACHE_DURATION', 3600); // 1 hour

// Development
define('DEBUG_MODE', false);
define('LOG_LEVEL', 'INFO');

// Production Settings
define('ENVIRONMENT', 'production');
define('MAINTENANCE_MODE', false);

// Error handling for production
if (!DEBUG_MODE) {
    error_reporting(0);
    ini_set('display_errors', 0);
    ini_set('log_errors', 1);
    ini_set('error_log', LOGS_DIR . 'error.log');
} else {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
}

// Set timezone
if (defined('TIMEZONE')) {
    date_default_timezone_set(TIMEZONE);
}

// Security headers
if (!headers_sent()) {
    header('X-Content-Type-Options: nosniff');
    header('X-Frame-Options: DENY');
    header('X-XSS-Protection: 1; mode=block');
    header('Referrer-Policy: strict-origin-when-cross-origin');
}

// Note: Direct access protection is handled by .htaccess file
?>";

        if (file_put_contents('config.php', $config_content)) {
            addStep("Created config.php");
        } else {
            addError("Failed to create config.php");
        }

        // Step 3: Skip sample post creation
        addStep("Skipped sample post creation");

        // Step 4: Create settings file
        $settings = [
            'site_title' => $site_title,
            'site_description' => $site_description,
            'admin_email' => $admin_email,
            'timezone' => $timezone,
            'posts_per_page' => 10,
            'enable_comments' => false,
            'enable_rss' => true,
            'enable_sitemap' => true,
            'theme' => 'default',
            'language' => 'en'
        ];

        if (file_put_contents('content/settings.json', json_encode($settings, JSON_PRETTY_PRINT))) {
            addStep("Created settings file");
        } else {
            addError("Failed to create settings file");
        }

        // Step 5: Create empty index.json
        $index_data = [];

        if (file_put_contents('content/index.json', json_encode($index_data, JSON_PRETTY_PRINT))) {
            addStep("Created empty content index");
        } else {
            addError("Failed to create content index");
        }

        // Step 6: Skip .htaccess creation (keeping existing file)
        addStep("Skipped .htaccess creation (keeping existing file)");

        // Step 7: Create robots.txt
        $robots_content = "User-agent: *
Disallow: /admin/
Disallow: /content/
Disallow: /logs/
Disallow: /libs/
Disallow: /uploads/
Allow: /uploads/featured/

Sitemap: " . rtrim($base_url, '/') . "/sitemap";

        if (file_put_contents('robots.txt', $robots_content)) {
            addStep("Created robots.txt");
        } else {
            addError("Failed to create robots.txt");
        }

        // Step 8: Set permissions (if possible)
        if (function_exists('chmod')) {
            $files_to_chmod = [
                'content' => 0755,
                'uploads' => 0755,
                'logs' => 0755,
                'config.php' => 0644,
                '.htaccess' => 0644
            ];

            foreach ($files_to_chmod as $file => $permission) {
                if (file_exists($file)) {
                    if (chmod($file, $permission)) {
                        addStep("Set permissions for $file");
                    } else {
                        addStep("Could not set permissions for $file (this is normal on some servers)", 'warning');
                    }
                }
            }
        }

        // Installation complete
        if ($success) {
            addStep("Installation completed successfully!");
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install FlatFile Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
</head>

<body>
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card shadow">
                    <div class="card-header bg-dark text-white text-center">
                        <div class="mb-3">
                            <i class="bi bi-gear-fill display-4"></i>
                        </div>
                        <h1 class="h2 mb-2">FlatFile Blog Installer</h1>
                        <p class="mb-0">Set up your new flat-file blog system</p>
                    </div>
                    <div class="card-body">

                        <?php if ($already_installed && $_SERVER['REQUEST_METHOD'] !== 'POST'): ?>
                            <!-- Already Installed Warning -->
                            <div class="card mb-4">
                                <div class="card-header bg-warning text-dark">
                                    <h5 class="mb-0">
                                        <i class="bi bi-exclamation-triangle me-2"></i>
                                        Blog Already Installed
                                    </h5>
                                </div>
                                <div class="card-body">
                                    <div class="alert alert-warning">
                                        <h6><i class="bi bi-info-circle me-2"></i>Installation Detected</h6>
                                        <p class="mb-3">A FlatFile blog installation has been detected on this server.</p>

                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="d-grid">
                                                    <a href="." class="btn btn-success">
                                                        <i class="bi bi-house me-2"></i>View Blog
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="d-grid">
                                                    <a href="admin" class="btn btn-primary">
                                                        <i class="bi bi-gear me-2"></i>Admin Panel
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="alert alert-danger">
                                        <h6><i class="bi bi-exclamation-triangle me-2"></i>Reinstall Option</h6>
                                        <p class="mb-3">If you want to start fresh, you can delete the existing installation and reinstall. <strong>This will delete all your blog posts, settings, and uploaded files!</strong></p>

                                        <form method="POST" class="d-inline">
                                            <input type="hidden" name="action" value="reinstall">
                                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete the existing installation? This action cannot be undone!')">
                                                <i class="bi bi-trash me-2"></i>Delete & Reinstall
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        <?php elseif ($_SERVER['REQUEST_METHOD'] === 'POST'): ?>
                            <!-- Installation Results -->
                            <div class="card mb-4">
                                <div class="card-header bg-<?php echo $success ? 'success' : 'danger'; ?> text-white">
                                    <h5 class="mb-0">
                                        <i class="bi bi-<?php echo $success ? 'check-circle' : 'exclamation-triangle'; ?> me-2"></i>
                                        Installation <?php echo $success ? 'Successful' : 'Failed'; ?>
                                    </h5>
                                </div>
                                <div class="card-body">
                                    <?php if (!empty($errors)): ?>
                                        <div class="alert alert-danger">
                                            <h6>Errors:</h6>
                                            <ul class="mb-0">
                                                <?php foreach ($errors as $error): ?>
                                                    <li><?php echo htmlspecialchars($error); ?></li>
                                                <?php endforeach; ?>
                                            </ul>
                                        </div>
                                    <?php endif; ?>

                                    <h6>Installation Steps:</h6>
                                    <div class="list-group">
                                        <?php foreach ($installation_steps as $step): ?>
                                            <div class="list-group-item d-flex align-items-center">
                                                <i class="bi bi-<?php echo $step['status'] === 'success' ? 'check-circle-fill text-success' : ($step['status'] === 'warning' ? 'exclamation-triangle-fill text-warning' : 'x-circle-fill text-danger'); ?> me-3"></i>
                                                <span><?php echo htmlspecialchars($step['step']); ?></span>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>

                                    <?php if ($success): ?>
                                        <div class="mt-4">
                                            <div class="alert alert-success">
                                                <h6><i class="bi bi-check-circle me-2"></i>Installation Complete!</h6>
                                                <p class="mb-2">Your FlatFile blog has been successfully installed.</p>
                                                <div class="d-grid gap-2 d-md-flex">
                                                    <a href="." class="btn btn-success">
                                                        <i class="bi bi-house me-2"></i>View Blog
                                                    </a>
                                                    <a href="admin/" class="btn btn-primary">
                                                        <i class="bi bi-gear me-2"></i>Admin Panel
                                                    </a>
                                                </div>
                                            </div>

                                            <div class="alert alert-info">
                                                <h6><i class="bi bi-info-circle me-2"></i>Next Steps:</h6>
                                                <ul class="mb-0">
                                                    <li>Delete this <code>install.php</code> file for security</li>
                                                    <li>Customize your blog settings in the admin panel</li>
                                                    <li>Create your first blog post</li>
                                                    <li>Set up your domain and hosting</li>
                                                </ul>
                                            </div>
                                        </div>
                                    <?php else: ?>
                                        <div class="mt-4">
                                            <div class="alert alert-danger">
                                                <h6><i class="bi bi-exclamation-triangle me-2"></i>Installation Failed</h6>
                                                <p>Please fix the errors above and try again.</p>
                                                <a href="install.php" class="btn btn-danger">
                                                    <i class="bi bi-arrow-clockwise me-2"></i>Try Again
                                                </a>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php else: ?>
                            <!-- Installation Form -->
                            <form method="POST" class="needs-validation" novalidate>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="site_title" class="form-label">
                                                <i class="bi bi-globe me-2"></i>Site Title
                                            </label>
                                            <input type="text" class="form-control" id="site_title" name="site_title"
                                                value="My FlatFile Blog" required>
                                            <div class="form-text">The name of your blog</div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="admin_username" class="form-label">
                                                <i class="bi bi-person me-2"></i>Admin Username
                                            </label>
                                            <input type="text" class="form-control" id="admin_username" name="admin_username"
                                                placeholder="admin" required>
                                            <div class="form-text">Your admin username</div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="admin_email" class="form-label">
                                                <i class="bi bi-envelope me-2"></i>Admin Email
                                            </label>
                                            <input type="email" class="form-control" id="admin_email" name="admin_email"
                                                placeholder="admin@example.com" required>
                                            <div class="form-text">Your email address</div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="timezone" class="form-label">
                                                <i class="bi bi-clock me-2"></i>Timezone
                                            </label>
                                            <select class="form-select" id="timezone" name="timezone" required>
                                                <option value="">Select Timezone</option>
                                                <option value="UTC">UTC</option>
                                                <option value="America/New_York">Eastern Time (ET)</option>
                                                <option value="America/Chicago">Central Time (CT)</option>
                                                <option value="America/Denver">Mountain Time (MT)</option>
                                                <option value="America/Los_Angeles">Pacific Time (PT)</option>
                                                <option value="Europe/London">London (GMT)</option>
                                                <option value="Europe/Paris">Paris (CET)</option>
                                                <option value="Asia/Tokyo">Tokyo (JST)</option>
                                                <option value="Asia/Shanghai">Shanghai (CST)</option>
                                                <option value="Asia/Kolkata">Mumbai (IST)</option>
                                                <option value="Australia/Sydney">Sydney (AEST)</option>
                                            </select>
                                            <div class="form-text">Your timezone</div>
                                        </div>
                                    </div>
                                </div>

                                <div class="mb-3">
                                    <label for="site_description" class="form-label">
                                        <i class="bi bi-text-paragraph me-2"></i>Site Description
                                    </label>
                                    <textarea class="form-control" id="site_description" name="site_description" rows="3"
                                        placeholder="A brief description of your blog">A simple, fast, and secure flat-file blog system built with PHP and Bootstrap.</textarea>
                                    <div class="form-text">Brief description of your blog</div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="admin_password" class="form-label">
                                                <i class="bi bi-lock me-2"></i>Admin Password
                                            </label>
                                            <input type="password" class="form-control" id="admin_password" name="admin_password"
                                                placeholder="Enter a secure password" minlength="6" required>
                                            <div class="form-text">Minimum 6 characters</div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="mb-3">
                                            <label for="base_url" class="form-label">
                                                <i class="bi bi-link-45deg me-2"></i>Base URL
                                            </label>
                                            <input type="url" class="form-control" id="base_url" name="base_url"
                                                value="<?php
                                                        $is_https = (
                                                            (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
                                                            || (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] == 443)
                                                            || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
                                                        );
                                                        $scheme = $is_https ? 'https://' : 'http://';
                                                        $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
                                                        $script_dir = rtrim(dirname($_SERVER['SCRIPT_NAME']), '/\\');
                                                        echo $scheme . $host . ($script_dir ? $script_dir : '');
                                                        ?>" required>
                                            <div class="form-text">Your blog's URL</div>
                                        </div>
                                    </div>
                                </div>

                                <div class="alert alert-info">
                                    <h6><i class="bi bi-info-circle me-2"></i>What will be installed:</h6>
                                    <ul class="mb-0">
                                        <li>Blog system files and directories</li>
                                        <li>Configuration files</li>
                                        <li>Sample blog post</li>
                                        <li>Admin panel setup</li>
                                        <li>Security configurations</li>
                                    </ul>
                                </div>

                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary btn-lg">
                                        <i class="bi bi-download me-2"></i>Install FlatFile Blog
                                    </button>
                                </div>
                            </form>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
        <script>
            // Form validation
            (function() {
                'use strict';
                window.addEventListener('load', function() {
                    var forms = document.getElementsByClassName('needs-validation');
                    var validation = Array.prototype.filter.call(forms, function(form) {
                        form.addEventListener('submit', function(event) {
                            if (form.checkValidity() === false) {
                                event.preventDefault();
                                event.stopPropagation();
                            }
                            form.classList.add('was-validated');
                        }, false);
                    });
                }, false);
            })();
        </script>
</body>

</html>